import type {
  User,
  StudentProfile,
  Subject,
  Chapter,
  Concept,
  Question,
  DailyMission,
  Weakness,
  AIInsight,
  StudyStreak,
  Achievement,
  TimetableSlot,
  QuestionOfDay,
} from '../types';

export const demoUser: User = {
  id: 'user-1',
  name: 'Aarav Kumar',
  email: 'aarav@example.com',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aarav',
  createdAt: new Date('2024-01-15'),
};

export const demoStudentProfile: StudentProfile = {
  userId: 'user-1',
  class: '12th Grade',
  board: 'CBSE',
  subjects: ['Physics', 'Mathematics', 'Chemistry'],
  strongSubjects: ['Mathematics'],
  weakSubjects: ['Chemistry'],
  learningGoals: ['Improve marks', 'Understand concepts', 'Prepare for board exams'],
  availableStudyTime: 120,
  learningPreferences: {
    visualLearner: true,
    practiceFirst: false,
    needsFrequentRevision: true,
    prefersDetailedExplanations: true,
  },
  onboardingCompleted: true,
};

export const demoSubjects: Subject[] = [
  {
    id: 'physics',
    name: 'Physics',
    icon: '⚛️',
    color: '#0ea5e9',
    overallMastery: 78,
    examReadiness: 72,
    chapters: [],
    weakAreas: ['Electric Potential', 'Magnetic Fields'],
    strongAreas: ['Newton\'s Laws', 'Work & Energy'],
  },
  {
    id: 'mathematics',
    name: 'Mathematics',
    icon: '📐',
    color: '#8b5cf6',
    overallMastery: 85,
    examReadiness: 81,
    chapters: [],
    weakAreas: ['Integration'],
    strongAreas: ['Differentiation', 'Trigonometry', 'Algebra'],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    icon: '🧪',
    color: '#10b981',
    overallMastery: 68,
    examReadiness: 64,
    chapters: [],
    weakAreas: ['Organic Chemistry', 'Chemical Kinetics'],
    strongAreas: ['Atomic Structure', 'Periodic Table'],
  },
];

export const physicsConcepts: Concept[] = [
  {
    id: 'concept-1',
    chapterId: 'chapter-1',
    name: 'Force and Motion',
    description: 'Understanding Newton\'s laws and their applications',
    status: 'mastered',
    mastery: 92,
    confidence: 90,
    importance: 9,
    prerequisites: [],
    relatedConcepts: ['concept-2'],
    lastPracticed: new Date('2024-08-30'),
    timesReviewed: 5,
    forgettingRisk: 15,
    errorCount: 2,
    independentSolveRate: 95,
  },
  {
    id: 'concept-2',
    chapterId: 'chapter-1',
    name: 'Vector Components',
    description: 'Breaking down vectors into components',
    status: 'weak',
    mastery: 62,
    confidence: 55,
    importance: 8,
    prerequisites: [],
    relatedConcepts: ['concept-1'],
    lastPracticed: new Date('2024-08-28'),
    timesReviewed: 3,
    forgettingRisk: 45,
    errorCount: 8,
    independentSolveRate: 60,
  },
  {
    id: 'concept-3',
    chapterId: 'chapter-2',
    name: 'Electric Potential',
    description: 'Understanding electric potential and potential difference',
    status: 'learning',
    mastery: 55,
    confidence: 50,
    importance: 9,
    prerequisites: ['concept-4'],
    relatedConcepts: ['concept-5'],
    lastPracticed: new Date('2024-09-01'),
    timesReviewed: 2,
    forgettingRisk: 35,
    errorCount: 5,
    independentSolveRate: 58,
  },
  {
    id: 'concept-4',
    chapterId: 'chapter-2',
    name: 'Electric Field',
    description: 'Concept of electric field and field lines',
    status: 'strong',
    mastery: 82,
    confidence: 78,
    importance: 10,
    prerequisites: [],
    relatedConcepts: ['concept-3'],
    lastPracticed: new Date('2024-08-29'),
    timesReviewed: 4,
    forgettingRisk: 20,
    errorCount: 3,
    independentSolveRate: 85,
  },
];

export const physicsChapters: Chapter[] = [
  {
    id: 'chapter-1',
    subjectId: 'physics',
    name: 'Laws of Motion',
    order: 1,
    description: 'Study of Newton\'s laws and their applications',
    status: 'mastered',
    mastery: 88,
    concepts: [physicsConcepts[0], physicsConcepts[1]],
    importantQuestions: [],
    previousYearQuestions: [],
    estimatedTime: 180,
    prerequisites: [],
  },
  {
    id: 'chapter-2',
    subjectId: 'physics',
    name: 'Electric Charges and Fields',
    order: 2,
    description: 'Understanding electric charges, fields, and potential',
    status: 'learning',
    mastery: 68,
    concepts: [physicsConcepts[2], physicsConcepts[3]],
    importantQuestions: [],
    previousYearQuestions: [],
    estimatedTime: 240,
    prerequisites: [],
  },
  {
    id: 'chapter-3',
    subjectId: 'physics',
    name: 'Magnetism and Matter',
    order: 3,
    description: 'Magnetic fields, magnetic materials, and Earth\'s magnetism',
    status: 'not_started',
    mastery: 0,
    concepts: [],
    importantQuestions: [],
    previousYearQuestions: [],
    estimatedTime: 200,
    prerequisites: ['chapter-2'],
  },
];

export const sampleQuestions: Question[] = [
  {
    id: 'q-1',
    conceptIds: ['concept-1'],
    text: 'A block of mass 5 kg is placed on a frictionless surface. What force is needed to accelerate it at 2 m/s²?',
    type: 'numerical',
    difficulty: 'easy',
    correctAnswer: '10 N',
    explanation: 'Using Newton\'s second law: F = ma = 5 kg × 2 m/s² = 10 N',
    hints: [
      'Which formula connects force, mass, and acceleration?',
      'Think about Newton\'s Second Law',
      'Try applying F = ma',
    ],
    previousYear: false,
    importance: 7,
    tags: ['newton-laws', 'force', 'acceleration'],
  },
  {
    id: 'q-2',
    conceptIds: ['concept-2'],
    text: 'A force of 50 N acts at an angle of 30° to the horizontal. Find the horizontal component.',
    type: 'numerical',
    difficulty: 'medium',
    correctAnswer: '43.3 N',
    explanation: 'Horizontal component = F cos θ = 50 × cos(30°) = 50 × 0.866 = 43.3 N',
    hints: [
      'How do you find components of a vector?',
      'Use trigonometric ratios',
      'Horizontal component = F × cos(angle)',
    ],
    previousYear: true,
    examPattern: 'CBSE Board 2023',
    importance: 8,
    tags: ['vectors', 'components', 'trigonometry'],
  },
];

export const demoDailyMission: DailyMission = {
  id: 'mission-1',
  userId: 'user-1',
  date: new Date(),
  totalEstimatedTime: 85,
  progress: 40,
  completed: false,
  tasks: [
    {
      id: 'task-1',
      type: 'learn',
      title: 'Complete Electric Potential concept',
      description: 'Learn the concept of electric potential and potential difference',
      reason: 'This is a fundamental concept for upcoming chapters',
      estimatedTime: 25,
      benefit: 'Will improve understanding of electrostatics by 15%',
      resourceId: 'concept-3',
      completed: true,
      priority: 9,
    },
    {
      id: 'task-2',
      type: 'revise',
      title: 'Review Vector Components',
      description: 'Revise vector decomposition and components',
      reason: 'Recent errors indicate weakening understanding',
      estimatedTime: 15,
      benefit: 'Prevents weakness from developing further',
      resourceId: 'concept-2',
      completed: true,
      priority: 8,
    },
    {
      id: 'task-3',
      type: 'practice',
      title: 'Solve 5 force problems',
      description: 'Practice Newton\'s laws application',
      reason: 'Maintains mastery level',
      estimatedTime: 20,
      benefit: 'Keeps strong concepts sharp',
      resourceId: 'concept-1',
      completed: false,
      priority: 6,
    },
    {
      id: 'task-4',
      type: 'assess',
      title: 'Take 10-minute diagnostic test',
      description: 'Quick assessment of Laws of Motion',
      reason: 'You\'re ready to test your understanding',
      estimatedTime: 10,
      benefit: 'Validates mastery and identifies gaps',
      resourceId: 'chapter-1',
      completed: false,
      priority: 7,
    },
    {
      id: 'task-5',
      type: 'practice',
      title: 'Practice Integration problems',
      description: 'Solve 3 integration questions',
      reason: 'Identified as weak area in Mathematics',
      estimatedTime: 15,
      benefit: 'Improves weak area mastery',
      resourceId: 'math-concept-1',
      completed: false,
      priority: 8,
    },
  ],
};

export const demoWeaknesses: Weakness[] = [
  {
    id: 'weak-1',
    conceptId: 'concept-2',
    userId: 'user-1',
    severity: 'moderate',
    detectedAt: new Date('2024-08-30'),
    errorPattern: 'Sign conversion errors in vector decomposition',
    rootCause: 'Unclear understanding of trigonometric sign conventions',
    resolved: false,
    recoveryPlan: {
      weaknessId: 'weak-1',
      currentStep: 2,
      progress: 40,
      estimatedTime: 45,
      steps: [
        {
          id: 'step-1',
          type: 'relearn',
          title: 'Review trigonometric ratios',
          description: 'Understand sin, cos, and their signs in different quadrants',
          completed: true,
        },
        {
          id: 'step-2',
          type: 'practice',
          title: 'Solve guided examples',
          description: 'Work through 3 guided vector decomposition problems',
          completed: true,
        },
        {
          id: 'step-3',
          type: 'practice',
          title: 'Independent practice',
          description: 'Solve 5 problems independently',
          completed: false,
        },
        {
          id: 'step-4',
          type: 'quiz',
          title: 'Mini quiz',
          description: 'Take a 5-question quiz on vectors',
          completed: false,
        },
        {
          id: 'step-5',
          type: 'retest',
          title: 'Final assessment',
          description: 'Verify recovery with comprehensive test',
          completed: false,
        },
      ],
    },
  },
  {
    id: 'weak-2',
    conceptId: 'concept-3',
    userId: 'user-1',
    severity: 'mild',
    detectedAt: new Date('2024-09-01'),
    errorPattern: 'Confusion between electric potential and electric field',
    rootCause: 'Similar terminology causing conceptual confusion',
    resolved: false,
  },
];

export const demoAIInsights: AIInsight[] = [
  {
    id: 'insight-1',
    userId: 'user-1',
    type: 'pattern',
    title: 'Performance improves with revision first',
    description: 'Your accuracy is 18% higher when you revise the concept before solving questions.',
    priority: 'medium',
    createdAt: new Date('2024-09-02'),
    read: false,
    actionable: true,
    actionLabel: 'Adjust learning strategy',
  },
  {
    id: 'insight-2',
    userId: 'user-1',
    type: 'improvement',
    title: 'Independence score increasing',
    description: 'You\'re using 30% fewer hints compared to last week. Great progress!',
    priority: 'low',
    createdAt: new Date('2024-09-01'),
    read: false,
    actionable: false,
  },
  {
    id: 'insight-3',
    userId: 'user-1',
    type: 'warning',
    title: 'Response time increasing',
    description: 'Your average response time for Electric Fields questions has increased by 25%. This may indicate developing uncertainty.',
    priority: 'high',
    createdAt: new Date('2024-08-31'),
    read: true,
    actionable: true,
    actionLabel: 'Review concept',
    actionUrl: '/learn/concept-4',
  },
];

export const demoStudyStreak: StudyStreak = {
  userId: 'user-1',
  currentStreak: 12,
  longestStreak: 21,
  lastStudyDate: new Date(),
  totalDays: 45,
};

export const demoAchievements: Achievement[] = [
  {
    id: 'ach-1',
    title: 'First Steps',
    description: 'Complete your first learning session',
    icon: '🎯',
    category: 'mastery',
    unlockedAt: new Date('2024-07-20'),
    progress: 1,
    target: 1,
  },
  {
    id: 'ach-2',
    title: 'Week Warrior',
    description: 'Maintain a 7-day study streak',
    icon: '🔥',
    category: 'consistency',
    unlockedAt: new Date('2024-08-15'),
    progress: 7,
    target: 7,
  },
  {
    id: 'ach-3',
    title: 'Independence Day',
    description: 'Reach 80% independence score',
    icon: '🎓',
    category: 'independence',
    unlockedAt: new Date('2024-08-28'),
    progress: 84,
    target: 80,
  },
  {
    id: 'ach-4',
    title: 'Master of One',
    description: 'Achieve 90%+ mastery in one chapter',
    icon: '⭐',
    category: 'mastery',
    unlockedAt: new Date('2024-08-25'),
    progress: 92,
    target: 90,
  },
  {
    id: 'ach-5',
    title: 'Speed Demon',
    description: 'Solve 10 questions in under 5 minutes each',
    icon: '⚡',
    category: 'speed',
    progress: 7,
    target: 10,
  },
  {
    id: 'ach-6',
    title: 'Century',
    description: 'Complete 100 practice questions',
    icon: '💯',
    category: 'mastery',
    progress: 73,
    target: 100,
  },
];

export const demoTimetable: TimetableSlot[] = [
  {
    id: 'slot-1',
    startTime: '08:30',
    endTime: '09:20',
    title: 'Universal Human Values 2: Understanding Harmony',
    status: 'done',
    color: '#8b5cf6',
    room: 'Hall 3',
  },
  {
    id: 'slot-2',
    startTime: '09:20',
    endTime: '10:10',
    title: 'Computer Organization and Architecture',
    status: 'done',
    color: '#0ea5e9',
    room: 'Lab B2',
  },
  {
    id: 'slot-3',
    startTime: '10:20',
    endTime: '11:10',
    title: 'Library & Guided Study',
    status: 'done',
    color: '#64748b',
    room: 'Central Library',
  },
  {
    id: 'slot-4',
    startTime: '11:45',
    endTime: '12:35',
    title: 'Artificial Intelligence and Decision Science',
    status: 'done',
    color: '#10b981',
    room: 'Auditorium 1',
  },
  {
    id: 'slot-5',
    startTime: '12:35',
    endTime: '13:25',
    title: 'Advanced Java Programming (Lab Integrated)',
    status: 'done',
    color: '#f59e0b',
    room: 'Software Lab 4',
  },
  {
    id: 'slot-6',
    startTime: '13:25',
    endTime: '14:15',
    title: 'Advanced Java Programming (Lab Integrated)',
    status: 'now',
    color: '#10b981',
    room: 'Software Lab 4',
  },
  {
    id: 'slot-7',
    startTime: '14:15',
    endTime: '15:05',
    title: 'Advanced Java Programming (Lab Integrated)',
    status: 'upcoming',
    color: '#6366f1',
    room: 'Software Lab 4',
  },
];

export const demoQuestionOfDay: QuestionOfDay = {
  id: 'qod-101',
  title: 'QUESTION OF THE DAY',
  category: 'Physics · Laws of Motion',
  difficulty: 'medium',
  xpReward: 20,
  questionText: 'A 5 kg block slides down a 30° inclined plane with coefficient of static friction μs = 0.4. What is the net parallel force tending to accelerate down the ramp?',
  options: [
    '16.97 N down the ramp',
    '7.53 N down the ramp',
    '24.50 N down the ramp',
    '0 N (Block remains static)',
  ],
  correctIndex: 1,
  explanation: 'Parallel gravity force Fg = mg sin(30°) = 5 × 9.8 × 0.5 = 24.5 N. Max static friction force f_max = μs mg cos(30°) = 0.4 × 5 × 9.8 × 0.866 = 16.97 N. Net force = 24.5 N - 16.97 N = 7.53 N down the ramp.',
};
